allowBuilds:
  core-js: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.112.1'
  - '@supabase/functions-js@2.112.1'
  - '@supabase/postgrest-js@2.112.1'
  - '@supabase/realtime-js@2.112.1'
  - '@supabase/storage-js@2.112.1'
  - '@supabase/supabase-js@2.112.1'
  - framer-motion@13.0.0
  - motion-dom@13.0.0
  - motion-utils@13.0.0
  - motion@13.0.0
